// Mock data for TurfMatch Phase 1 — extends to match repo UI/UX.
// Pune-centric coordinates, availability, reliability, brackets, fixtures, balls.

import type {
  AppNotification,
  BallEvent,
  BracketMatch,
  BracketTeam,
  ChatMessage,
  ChatThread,
  Ground,
  LiveScorecard,
  Match,
  MatchJoinRequest,
  Player,
  Tournament,
  TournamentFixture,
} from "./types"

export const PLAYERS: Player[] = [
  {
    id: "p1",
    name: "Rahul Sharma",
    avatar: "https://i.pravatar.cc/240?u=rahul",
    role: "Batsman",
    city: "Pune",
    zone: "Baner",
    rating: 4.8,
    reliability: 98,
    level: 42,
    badge: "Elite",
    careerStats: {
      matches: 142,
      winRatePct: 76,
      runs: 3450,
      runsTopPercentile: 5,
      wickets: 12,
    },
    recentForm: [
      { result: "W", vsTeam: "Royal Strikers", margin: "by 18 runs" },
      { result: "W", vsTeam: "Baner XI", margin: "by 6 wkts" },
      { result: "L", vsTeam: "Hinjewadi Hawks", margin: "by 4 wkts" },
    ],
    availability: "today",
    distanceKm: 0,
    isFriend: false,
  },
  {
    id: "p2",
    name: "Aman Verma",
    avatar: "https://i.pravatar.cc/240?u=aman",
    role: "All-Rounder",
    city: "Pune",
    zone: "Wakad",
    rating: 4.6,
    reliability: 95,
    level: 31,
    badge: "Pro",
    careerStats: {
      matches: 88,
      winRatePct: 64,
      runs: 1820,
      wickets: 65,
      economy: 7.2,
    },
    recentForm: [
      { result: "W", vsTeam: "Aundh Lions", margin: "by 22 runs" },
      { result: "L", vsTeam: "Kothrud Kings", margin: "by 3 wkts" },
      { result: "W", vsTeam: "Camp Crusaders", margin: "by 8 runs" },
    ],
    availability: "tomorrow",
    distanceKm: 1.6,
    isFriend: true,
  },
  {
    id: "p3",
    name: "Vikram Singh",
    avatar: "https://i.pravatar.cc/240?u=vikram",
    role: "Bowler",
    city: "Pune",
    zone: "Hinjewadi",
    rating: 4.9,
    reliability: 100,
    level: 55,
    badge: "Elite",
    careerStats: {
      matches: 160,
      winRatePct: 71,
      runs: 410,
      wickets: 220,
      economy: 6.4,
    },
    recentForm: [
      { result: "W", vsTeam: "Pune Strikers", margin: "by 12 runs" },
      { result: "W", vsTeam: "Wakad Warriors", margin: "by 5 wkts" },
      { result: "W", vsTeam: "Baner Blasters", margin: "by 2 wkts" },
    ],
    availability: "this_weekend",
    distanceKm: 9.4,
    isFriend: true,
  },
  {
    id: "p4",
    name: "Karan Patel",
    avatar: "https://i.pravatar.cc/240?u=karan",
    role: "Wicket-Keeper",
    city: "Pune",
    zone: "Kothrud",
    rating: 4.5,
    reliability: 82,
    level: 24,
    badge: "Rising",
    careerStats: {
      matches: 56,
      winRatePct: 58,
      runs: 980,
      wickets: 0,
    },
    recentForm: [
      { result: "L", vsTeam: "Camp Crusaders", margin: "by 4 wkts" },
      { result: "W", vsTeam: "Hadapsar XI", margin: "by 3 runs" },
      { result: "L", vsTeam: "Hinjewadi Hawks", margin: "by 6 wkts" },
    ],
    availability: "not_available",
    distanceKm: 4.7,
    isFriend: false,
  },
  {
    id: "p5",
    name: "Priya Iyer",
    avatar: "https://i.pravatar.cc/240?u=priya",
    role: "All-Rounder",
    city: "Pune",
    zone: "Viman Nagar",
    rating: 4.4,
    reliability: 88,
    level: 19,
    badge: "Rising",
    careerStats: {
      matches: 38,
      winRatePct: 60,
      runs: 720,
      wickets: 22,
      economy: 7.8,
    },
    recentForm: [
      { result: "W", vsTeam: "Eastside XI", margin: "by 14 runs" },
      { result: "W", vsTeam: "Kalyani Kings", margin: "by 5 wkts" },
      { result: "L", vsTeam: "Baner Blasters", margin: "by 7 runs" },
    ],
    availability: "today",
    distanceKm: 6.2,
    isFriend: false,
  },
  {
    id: "p6",
    name: "Sameer Khan",
    avatar: "https://i.pravatar.cc/240?u=sameer",
    role: "Bowler",
    city: "Pune",
    zone: "Hadapsar",
    rating: 4.7,
    reliability: 92,
    level: 36,
    badge: "Pro",
    careerStats: {
      matches: 102,
      winRatePct: 67,
      runs: 380,
      wickets: 145,
      economy: 6.9,
    },
    recentForm: [
      { result: "W", vsTeam: "Hinjewadi Hawks", margin: "by 4 runs" },
      { result: "L", vsTeam: "Pune Strikers", margin: "by 2 wkts" },
      { result: "W", vsTeam: "Aundh Lions", margin: "by 9 runs" },
    ],
    availability: "tomorrow",
    distanceKm: 11.3,
    isFriend: false,
  },
  {
    id: "p7",
    name: "Amit Patel",
    avatar: "https://i.pravatar.cc/240?u=amit",
    role: "Batsman",
    city: "Pune",
    zone: "Aundh",
    rating: 4.2,
    reliability: 72,
    level: 14,
    badge: "Rising",
    careerStats: { matches: 28, winRatePct: 50, runs: 540, wickets: 4 },
    recentForm: [
      { result: "L", vsTeam: "Wakad Warriors", margin: "by 6 wkts" },
      { result: "W", vsTeam: "Baner XI", margin: "by 22 runs" },
    ],
    availability: "this_weekend",
    distanceKm: 3.1,
    isFriend: false,
  },
]

// Logged-in user is the first player.
export const ME: Player = PLAYERS[0]

export const GROUNDS: Ground[] = [
  {
    id: "g1",
    name: "Legends Turf",
    location: "Baner, Pune",
    zone: "Baner",
    distanceKm: 2.4,
    rating: 4.8,
    pricePerHour: 1200,
    image:
      "https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?auto=format&fit=crop&w=1200&q=80",
    features: ["Floodlights", "Dugout", "Washroom", "Parking"],
    availableSlots: ["06:00 AM", "08:00 PM", "09:00 PM"],
    category: "Box Cricket",
    pitchType: "Astroturf",
    verified: true,
    upiReady: true,
    liveTeamsToday: 12,
    lat: 18.5615,
    lng: 73.7807,
  },
  {
    id: "g2",
    name: "The Dugout Arena",
    location: "Viman Nagar, Pune",
    zone: "Viman Nagar",
    distanceKm: 5.1,
    rating: 4.6,
    pricePerHour: 1500,
    image:
      "https://images.unsplash.com/photo-1518605368461-1ee7e550b55b?auto=format&fit=crop&w=1200&q=80",
    features: ["Astroturf", "Cafe", "Parking"],
    availableSlots: ["07:00 AM", "10:00 PM"],
    category: "Box Cricket",
    pitchType: "Astroturf",
    verified: true,
    upiReady: true,
    liveTeamsToday: 8,
    lat: 18.5683,
    lng: 73.9143,
  },
  {
    id: "g3",
    name: "Strikers Box",
    location: "Kalyani Nagar, Pune",
    zone: "Kalyani Nagar",
    distanceKm: 6.8,
    rating: 4.9,
    pricePerHour: 1800,
    image:
      "https://images.unsplash.com/photo-1629814436531-50a0f670e280?auto=format&fit=crop&w=1200&q=80",
    features: ["Premium Turf", "Floodlights", "Showers", "Equipment"],
    availableSlots: ["05:00 PM", "06:00 PM", "11:00 PM"],
    category: "Box Cricket",
    pitchType: "Astroturf",
    verified: true,
    upiReady: false,
    liveTeamsToday: 15,
    lat: 18.5485,
    lng: 73.9012,
  },
  {
    id: "g4",
    name: "Greenfield Cricket Hub",
    location: "Hinjewadi, Pune",
    zone: "Hinjewadi",
    distanceKm: 9.2,
    rating: 4.5,
    pricePerHour: 1100,
    image:
      "https://images.unsplash.com/photo-1531415074968-036ba1b575da?auto=format&fit=crop&w=1200&q=80",
    features: ["Astroturf", "Floodlights", "Parking"],
    availableSlots: ["06:00 PM", "08:00 PM"],
    category: "Full Ground",
    pitchType: "Hard Pitch",
    verified: true,
    upiReady: true,
    liveTeamsToday: 4,
    lat: 18.5912,
    lng: 73.7389,
  },
  {
    id: "g5",
    name: "Net Practice Pro",
    location: "Kothrud, Pune",
    zone: "Kothrud",
    distanceKm: 4.1,
    rating: 4.5,
    pricePerHour: 400,
    image:
      "https://images.unsplash.com/photo-1599058917212-d750089bc07e?auto=format&fit=crop&w=1200&q=80",
    features: ["Bowling Machine", "Multiple Nets", "Shaded"],
    availableSlots: ["06:00 AM", "07:00 AM", "07:00 PM"],
    category: "Net Practice",
    pitchType: "Dusty Pitch",
    verified: true,
    upiReady: true,
    liveTeamsToday: 5,
    lat: 18.5074,
    lng: 73.8077,
  },
]

const RULES_DEFAULT = [
  "White leather ball will be provided by the organizer.",
  "Players must report 15 minutes before the start time.",
  "Full whites or sports jerseys mandatory.",
]

export const MATCHES: Match[] = [
  {
    id: "m1",
    title: "Friday Night Box",
    ground: GROUNDS[0],
    startsAt: "Tonight, 8:00 PM",
    date: "Oct 24",
    startsInLabel: "LIVE IN 2H",

    skillLevel: "Intermediate",
    visibility: "public",
    totalSlots: 14,
    filledSlots: 11,
    pricePerPlayer: 150,
    organizer: PLAYERS[0],
    players: [PLAYERS[0], PLAYERS[1], PLAYERS[2], PLAYERS[4], PLAYERS[6]],
    rules: RULES_DEFAULT,
    status: "filling_fast",
    score: { teamA: 142, wicketsA: 4, oversA: 14.2, teamB: 0 },
    liveBalls: ["4", "1", "W", "0", "6", "1"],
  },
  {
    id: "m2",
    title: "Saturday Morning XI",
    ground: GROUNDS[1],
    startsAt: "Tomorrow, 7:00 AM",
    date: "Oct 25",
    startsInLabel: "STARTS IN 14H",

    skillLevel: "Pro",
    visibility: "public",
    totalSlots: 22,
    filledSlots: 21,
    pricePerPlayer: 200,
    organizer: PLAYERS[2],
    players: [PLAYERS[2], PLAYERS[3], PLAYERS[5]],
    rules: RULES_DEFAULT,
    status: "filling_fast",
    score: null,
  },
  {
    id: "m3",
    title: "Sunday Premier Box",
    ground: GROUNDS[2],
    startsAt: "Sun, 5:00 PM",
    date: "Oct 26",

    skillLevel: "Intermediate",
    visibility: "public",
    totalSlots: 16,
    filledSlots: 8,
    pricePerPlayer: 175,
    organizer: PLAYERS[3],
    players: [PLAYERS[3], PLAYERS[5], PLAYERS[1]],
    rules: RULES_DEFAULT,
    status: "open",
    score: null,
  },
  {
    id: "m4",
    title: "Hinjewadi Full Ground",
    ground: GROUNDS[3],
    startsAt: "Sat, 11:00 AM",
    date: "Oct 25",

    skillLevel: "Pro",
    visibility: "public",
    totalSlots: 22,
    filledSlots: 22,
    pricePerPlayer: 250,
    organizer: PLAYERS[2],
    players: PLAYERS.slice(0, 6),
    rules: RULES_DEFAULT,
    status: "locked",
    score: null,
  },
]

export const JOIN_REQUESTS: MatchJoinRequest[] = [
  {
    id: "jr1",
    matchId: "m1",
    player: PLAYERS[0],
    status: "pending",
    requestedAt: "2 mins ago",
  },
  {
    id: "jr2",
    matchId: "m1",
    player: PLAYERS[2],
    status: "pending",
    requestedAt: "12 mins ago",
  },
  {
    id: "jr3",
    matchId: "m1",
    player: PLAYERS[6],
    status: "pending",
    requestedAt: "1 hr ago",
  },
]

// ── Tournaments + brackets + fixtures ────────────────────────────────────────

const TEAM = (
  id: string,
  name: string,
  shortCode: string,
  logoColor: string,
  score: number | "-" | undefined = undefined,
): BracketTeam => ({ id, name, shortCode, logoColor, score })

const BRACKET_T1: BracketMatch[] = [
  {
    id: "b1",
    round: "QF",
    teamA: TEAM("dk", "Deccan Knights", "DK", "#4edea3", 185),
    teamB: TEAM("ps", "Pune Strikers", "PS", "#ffb95f", 142),
    winnerId: "dk",
  },
  {
    id: "b2",
    round: "QF",
    teamA: TEAM("mg", "Maratha Gladiators", "MG", "#71a1ff", "-"),
    teamB: TEAM("st", "Shivaji Titans", "ST", "#ffb4ab", "-"),
    isLive: true,
  },
  {
    id: "b3",
    round: "QF",
    teamA: TEAM("bw", "Bandra Warriors", "BW", "#adc6ff", "-"),
    teamB: TEAM("nc", "Navi Challengers", "NC", "#ee9800", "-"),
  },
  {
    id: "b4",
    round: "QF",
    teamA: TEAM("kk", "Kothrud Kings", "KK", "#10b981", "-"),
    teamB: TEAM("hh", "Hinjewadi Hawks", "HH", "#ffddb8", "-"),
  },
  {
    id: "b5",
    round: "SF",
    teamA: TEAM("dk", "Deccan Knights", "DK", "#4edea3", "-"),
    teamB: TEAM("?", "Winner QF 2", "?", "#3c4a42", "-"),
    isPending: true,
    pendingLabel: "Winner QF 2",
  },
]

const FIXTURES_T1: TournamentFixture[] = [
  {
    id: "f1",
    label: "QUARTER FINAL 2",
    time: "LIVE NOW",
    isLive: true,
    teamA: { ...TEAM("mg", "Maratha Gladiators", "MG", "#71a1ff", 112), state: "112/4" },
    teamB: { ...TEAM("st", "Shivaji Titans", "ST", "#ffb4ab"), state: "Yet to bat" },
    oversInfo: "OVERS: 14.2/20",
  },
  {
    id: "f2",
    label: "QUARTER FINAL 3",
    time: "8:00 PM",
    teamA: TEAM("bw", "Bandra Warriors", "BW", "#adc6ff"),
    teamB: TEAM("nc", "Navi Challengers", "NC", "#ee9800"),
  },
]

export const TOURNAMENTS: Tournament[] = [
  {
    id: "t1",
    name: "Pune Premier League",
    status: "Live",
    prize: "₹50,000",
    prizeAmount: 50000,
    dates: "Oct 15 - Nov 5",
    startsAt: "Starts Oct 15",
    format: "16 Teams · Knockout",
    teamsRegistered: 14,
    teamsTotal: 16,
    registrationClosesIn: "48 hours",
    entryFee: 2500,
    image:
      "https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?auto=format&fit=crop&w=1200&q=80",
    rules: [
      "8 overs per innings",
      "Knockout format",
      "White leather ball provided",
      "Teams must report 30 mins prior",
    ],
    bracket: BRACKET_T1,
    fixtures: FIXTURES_T1,
  },
  {
    id: "t2",
    name: "Pune Corporate League",
    status: "Registering",
    prize: "₹1,00,000",
    prizeAmount: 100000,
    dates: "Nov 1 - Nov 15",
    startsAt: "Starts Nov 1",
    format: "16 Teams · League + Knockout",
    teamsRegistered: 12,
    teamsTotal: 16,
    registrationClosesIn: "5 days",
    entryFee: 5000,
    image:
      "https://images.unsplash.com/photo-1531415074968-036ba1b575da?auto=format&fit=crop&w=1200&q=80",
    rules: [
      "11v11 Hard Tennis Ball",
      "8 overs per innings",
      "Teams must report 30 mins prior",
      "Entry fee non-refundable after team lock",
    ],
    bracket: [],
    fixtures: [],
  },
]

// ── Live scorecard mock ──────────────────────────────────────────────────────

const RECENT_BALLS: BallEvent[] = [
  { id: "ball1", label: "4" },
  { id: "ball2", label: "1" },
  { id: "ball3", label: "W", isWicket: true },
  { id: "ball4", label: "0" },
  { id: "ball5", label: "6" },
  { id: "ball6", label: "1" },
]

export const LIVE_SCORECARD: LiveScorecard = {
  matchId: "m1",
  innings: 1,
  overLabel: "OVER 14.2",
  teamABBattingLabel: "MUMBAI STRIKERS vs DELHI INVINCIBLES",
  totalRuns: 142,
  totalWickets: 4,
  currentRunRate: 9.9,
  projected: 195,
  target: null,
  recentBalls: RECENT_BALLS,
  striker: {
    id: "p1",
    name: "Rohit S.",
    isStriker: true,
    runs: 45,
    balls: 24,
    fours: 3,
    sixes: 2,
  },
  nonStriker: {
    id: "p5",
    name: "Surya Y.",
    isStriker: false,
    runs: 12,
    balls: 8,
    fours: 1,
    sixes: 0,
  },
  bowler: {
    id: "p3",
    name: "Jasprit B.",
    overs: "2.2",
    maidens: 0,
    runs: 18,
    wickets: 1,
    economy: 7.71,
  },
}

// ── Notifications, chat ──────────────────────────────────────────────────────

export const NOTIFICATIONS: AppNotification[] = [
  {
    id: "n1",
    kind: "match_reminder",
    title: "Match in 2 hours",
    body: "Friday Night Box at Legends Turf — locking soon.",
    time: "2h",
    read: false,
    actorAvatar: GROUNDS[0].image,
  },
  {
    id: "n2",
    kind: "match_join",
    title: "Aman joined your match",
    body: "Aman Verma confirmed for Saturday Morning XI.",
    time: "5h",
    read: false,
    actorAvatar: PLAYERS[1].avatar,
  },
  {
    id: "n3",
    kind: "tournament",
    title: "Pune Corporate League",
    body: "12 of 16 team slots filled. Register your team now.",
    time: "Yesterday",
    read: true,
  },
  {
    id: "n4",
    kind: "friend_request",
    title: "Vikram added you",
    body: "Vikram Singh added you as a teammate.",
    time: "2d",
    read: true,
    actorAvatar: PLAYERS[2].avatar,
  },
]

export const CHAT_THREADS: ChatThread[] = [
  {
    id: "c1",
    matchId: "m1",
    title: "Legends 8PM Game",
    lastMessage: "Rahul: I am bringing the heavy ball.",
    lastMessageTime: "10m",
    unread: 3,
    isLive: true,
  },
  {
    id: "c2",
    matchId: "m2",
    title: "Saturday Morning XI",
    lastMessage: "Vikram: Reach by 6:45 AM, gates open.",
    lastMessageTime: "1h",
    unread: 0,
    isLive: false,
  },
]

export const CHAT_MESSAGES: ChatMessage[] = [
  {
    id: "msg-system-1",
    authorId: "system",
    authorName: "System",
    authorAvatar: "",
    text: "Match booked at Legends Turf · 10 mins ago",
    time: "9:30 AM",
    kind: "system",
  },
  {
    id: "msg1",
    authorId: "p3",
    authorName: "Vikram Singh",
    authorAvatar: PLAYERS[2].avatar,
    text: "Boys, who's bringing the bats? I have 2.",
    time: "9:32 AM",
  },
  {
    id: "msg2",
    authorId: "p1",
    authorName: "Rahul Sharma",
    authorAvatar: PLAYERS[0].avatar,
    text: "I've got a new pack of Kookaburra balls. Bringing them!",
    time: "9:34 AM",
    isMine: true,
    read: true,
  },
  {
    id: "msg3",
    authorId: "p2",
    authorName: "Aman Verma",
    authorAvatar: PLAYERS[1].avatar,
    text: "Perfect. @Rahul, don't worry about it. I'm reaching in 5 mins.",
    time: "9:36 AM",
  },
  {
    id: "msg-system-2",
    authorId: "system",
    authorName: "System",
    authorAvatar: "",
    text: "Aman Verma is now at the turf!",
    time: "9:42 AM",
    kind: "location",
  },
]
